// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB57Y-yQlroDy35aXG7BlIj0DjLTAST_Cs',
    appId: '1:1058649520805:web:2c664d372dca909443ab4c',
    messagingSenderId: '1058649520805',
    projectId: 'foodpool-1de3b',
    authDomain: 'foodpool-1de3b.firebaseapp.com',
    storageBucket: 'foodpool-1de3b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-bUjOi4N-EP3DizBVjKbKaaioV7artc8',
    appId: '1:1058649520805:android:42f09d8e5837c3b543ab4c',
    messagingSenderId: '1058649520805',
    projectId: 'foodpool-1de3b',
    storageBucket: 'foodpool-1de3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIcdRkaS-5PXWgoNWhw_8i-yg8JTg3Mj0',
    appId: '1:1058649520805:ios:82be153dbdc37fbe43ab4c',
    messagingSenderId: '1058649520805',
    projectId: 'foodpool-1de3b',
    storageBucket: 'foodpool-1de3b.firebasestorage.app',
    iosClientId: '1058649520805-032hb4eel0ucvscndkfpr4emi2f971kv.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodpool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIcdRkaS-5PXWgoNWhw_8i-yg8JTg3Mj0',
    appId: '1:1058649520805:ios:82be153dbdc37fbe43ab4c',
    messagingSenderId: '1058649520805',
    projectId: 'foodpool-1de3b',
    storageBucket: 'foodpool-1de3b.firebasestorage.app',
    iosClientId: '1058649520805-032hb4eel0ucvscndkfpr4emi2f971kv.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodpool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB57Y-yQlroDy35aXG7BlIj0DjLTAST_Cs',
    appId: '1:1058649520805:web:59056aeac7c7f67743ab4c',
    messagingSenderId: '1058649520805',
    projectId: 'foodpool-1de3b',
    authDomain: 'foodpool-1de3b.firebaseapp.com',
    storageBucket: 'foodpool-1de3b.firebasestorage.app',
  );
}
